---
- name: restart freeradius
  ansible.builtin.systemd:
    name: freeradius
    state: restarted

- name: restart accel-ppp
  ansible.builtin.systemd:
    name: accel-pppd.service
    daemon_reload: true
    state: restarted
