"""
bng_subscriber_agent.py — persistent per-subscriber session + attack-
traffic control daemon, run on `suscriptor` (Broadband domain,
distributed VM lab). REPLACES simulation/bng_agent.py's BNGBlaster
wrapper -- see bngblaster_broadband_pipeline_status memory for why:
BNGBlaster's own sendto() succeeded but the frame was invisible to
every external observer on this lab, an unresolved bug. This project's
real BNG-side telemetry now comes from FreeRADIUS's own accounting
records on `bng` itself (telemetry/broadband_adapter.py tails those
over SSH) -- this daemon's only job is making real IPoE-backed
subscriber sessions exist against accel-ppp and driving real attack
traffic sourced from each subscriber's own DHCP-assigned IP.

A "subscriber session" here is one macvlan sub-interface (roles/
suscriptor's setup_macvlans.sh.j2 creates macvlan1..N at boot, each
with its own MAC) running its own `dhclient` -- accel-ppp's ipoe module
on `bng` sees each as a distinct client (by Calling-Station-Id = MAC),
authenticates+accounts it via FreeRADIUS, and hands back a real IPv4
lease. `dhclient -r` (release) on stop sends a real DHCPRELEASE, which
is what makes FreeRADIUS emit a real Accounting-Stop record for that
session -- a genuine BNG-native session teardown, not a synthetic one.

This project also went through a PPPoE/pppd phase in between: an
earlier IPoE test showed accel-ppp's own ipoeN session interfaces never
counting real attack traffic under load (RX stuck at exactly 0 no
matter how much traffic flowed), which looked like a kernel ipoe.ko
classification bug, so the whole stack was rebuilt around PPPoE
instead. It wasn't the kernel driver. Confirmed on a later real run:
`suscriptor` is dual-homed (a management NIC besides the access-side
one each macvlanN rides on), and with no explicit routing override the
kernel's normal destination-based route lookup sent subscriber-sourced
attack traffic out the OTHER NIC entirely -- it never reached `bng`'s
access interface at all, so accel-ppp's ipoe.ko never got a chance to
see it. Subscriber._add_source_route() below is that override: a
per-subscriber `ip rule`/`ip route`, forcing traffic sourced from each
subscriber's own IP out its own macvlanN interface via `bng`'s real
gateway. Once in place, a real flood correctly moved a session's ipoeN
RX counters by ~200k packets in 8 seconds -- accel-ppp's accounting was
fine all along, and PPPoE's extra complexity (pppd, PAP, Van Jacobson
compression workarounds) turned out to be unnecessary. IPoE is simpler
for this project's actual point (real accounting telemetry): a
DHCP-leased macvlan interface is just an ordinary Ethernet-type
netdevice, no PPP-specific quirks to work around.

TCP_SYN/UDP attack traffic is generated by simulation/bng_flood.py
(spawned as a subprocess), NOT hping3 -- confirmed on a real run that
hping3 cannot reliably deliver traffic here at all: with no explicit
interface bind it picks the wrong NIC entirely (ignoring the very `ip
rule` this module sets up), and even with an explicit interface bind it
silently fails to actually reach the destination (this was tested both
over a PPP interface, where hping3's raw injection assumes Ethernet
framing PPP doesn't have, and over a plain macvlan/Ethernet interface,
where it still failed, apparently never resolving ARP correctly). See
bng_flood.py's own module docstring for the full diagnosis. ICMP still
shells out to the system `ping` binary, which already worked correctly
throughout this project's debugging (it's genuine kernel-stack traffic,
not a raw L2 injection).

Same tiny plain-text FIFO protocol as its predecessor (one command per
line): "baseline", "attack <scenario>", "stop", "stop_all" -- driven
over SSH by webtool/bng_ops.py's BngLifecycle in distributed mode
(_ssh_write_fifo), unchanged on that end. One new command since:
"kick <ip>", sent by telemetry/broadband_adapter.py's own
apply_mitigation() right after a real unblock -- see
Subscriber.force_refresh()'s own docstring for why.

Also serves a tiny read-only HTTP endpoint (_StateHTTPHandler below,
GET /active_scenario on _HTTP_PORT) -- telemetry/broadband_adapter.py's
distributed-mode collect() polls this every cycle instead of SSHing in
a `cat` of _STATE_PATH, since that file changes only on attack start/
stop and a fresh SSH connection per poll (confirmed ~0.5s of handshake
alone) was pure overhead for reading the same unchanged bytes almost
every time.

A background thread (see run()/_resync_loop) periodically re-checks
every subscriber's real interface IP against what this daemon has
cached and re-syncs routing/the running attack process/the state file
if it changed -- confirmed on a real run that accel-ppp's IPoE pool
allocation does NOT reliably keep handing the same MAC the same IP
across successive DHCP transactions, repeatedly reassigning a LIVE
subscriber's address independent of dhclient's own lease-renewal timer.
Without this, self.ip goes silently stale and the attack process keeps
binding to an address no longer assigned to any local interface,
generating zero real traffic with no visible error anywhere -- see
Subscriber.resync_ip()'s own docstring for the full story.

Usage (on suscriptor, as root -- dhclient/ping/raw sockets need it):
  sudo python3 simulation/bng_subscriber_agent.py \\
      --target-ip 10.10.0.100 --gateway-ip 10.20.0.1 \\
      --parent-interface ens192 --fifo /run/bng-agent/cmd
"""

import argparse
import json
import os
import re
import subprocess
import sys
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

REPO_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_DIR)
from simulation.bng_ipoe_config import SCENARIOS, SCENARIO_PARAMS, BASELINE_SCENARIO, build_scenario  # noqa: E402

_MAX_SUBSCRIBERS = 8
_DHCP_RUN_DIR = "/run/bng-subscribers"
_DHCP_WAIT_S = 15
# How often the background thread (see run()) checks every subscriber's
# real interface IP against what this daemon has cached, to catch the
# IP-drift Subscriber.resync_ip() documents. FreeRADIUS's own
# acct-interim-interval (roles/bng's accel-ppp.conf.j2) is 5s -- no
# point checking meaningfully faster than that, since accounting-based
# detection can't observe a resync happening any sooner anyway.
_RESYNC_INTERVAL_S = 5
# Real per-session byte/packet counters come from FreeRADIUS's own
# accounting on `bng` (telemetry/broadband_adapter.py tails those) --
# but RADIUS accounting has no L4 visibility at all (it's a volumetric
# total, not a flow breakdown), same limitation BNGBlaster's own
# session-streams had (see simulation/bng_config.py's old module
# docstring: "the synthetic producer already knows what it's
# simulating"). This state file is that same convention's new home --
# broadband_adapter.py's distributed-mode collect() ALSO reads this
# (over plain HTTP now, not SSH -- see _StateHTTPHandler below) to learn
# which protocol/dst_port each currently-attacking subscriber's IP is
# meant to represent, merging it with FreeRADIUS's real rate data by IP.
_STATE_PATH = f"{_DHCP_RUN_DIR}/active_scenario.json"

# Must match settings.BNG_DIST_SUSCRIPTOR_HTTP_PORT. A fixed local
# constant, not a CLI flag -- this is an internal detail of the
# protocol between this daemon and broadband_adapter.py, not a
# deployment-specific choice the way --target-ip/--gateway-ip are.
_HTTP_PORT = 8765

_FLOOD_SCRIPT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "bng_flood.py")
# Shared by every attack subprocess (Subscriber.start_attack(), below)
# -- was DEVNULL before, see that method's own comment for why that hid
# a real bug (bng_flood.py's udp_flood() failing every single call,
# silently) for a long time.
_FLOOD_LOG_PATH = "/var/log/bng-flood.log"


def _iface(n: int) -> str:
    return f"macvlan{n}"


def _pidfile(n: int) -> str:
    # NOT under _DHCP_RUN_DIR -- confirmed on a real run: Ubuntu's
    # stock dhclient AppArmor profile (/etc/apparmor.d/sbin.dhclient)
    # only allows /run/dhclient*.pid and /run/dhclient*.lease* directly
    # under /run/, not a subdirectory -- dhclient still gets a real
    # lease with a custom -pf/-lf path (the DHCP exchange itself isn't
    # gated by AppArmor), but silently fails to WRITE its pid/lease
    # files there ("Permission denied"), breaking session_down()'s own
    # -r (release) call, which depends on those files.
    return f"/run/dhclient-{_iface(n)}.pid"


def _leasefile(n: int) -> str:
    return f"/run/dhclient-{_iface(n)}.leases"


# Source-based routing table/rule per subscriber -- what makes the
# kernel's own FIB lookup deliver traffic bound to this subscriber's IP
# out its own macvlanN interface instead of whatever `suscriptor`'s
# other (management) NIC's own destination-based route would otherwise
# pick (see this module's own top-of-file comment).
def _route_table(n: int) -> int:
    return 100 + n


def _rule_priority(n: int) -> int:
    return 200 + n


def _run_ip(args: list) -> None:
    """Confirmed on a real run: this used to only catch TimeoutExpired/
    OSError (subprocess.run itself failing to launch) and never checked
    the actual `ip` command's own exit code -- a non-zero return (e.g.
    `ip rule add` silently rejected, or racing an interface that isn't
    up yet) produced no error anywhere, so a missing per-subscriber
    source-route rule looked identical to a healthy one in every log.
    That's exactly how the missing `ip rule` for the active broadband
    attacker went unnoticed (traffic silently routed out suscriptor's
    MGMT NIC instead of via `bng`, zero FreeRADIUS accounting, zero
    detection) -- see docs/vlan-backbone.md and this session's own
    broadband domain-test investigation."""
    try:
        result = subprocess.run(["ip", *args], capture_output=True, text=True, timeout=5)
    except (subprocess.TimeoutExpired, OSError) as exc:
        print(f"[SUBSCRIBER] ip {' '.join(args)} failed: {exc}", file=sys.stderr)
        return
    if result.returncode != 0:
        print(
            f"[SUBSCRIBER] ip {' '.join(args)} exited {result.returncode}: {result.stderr.strip()}",
            file=sys.stderr,
        )


def _read_iface_ip(iface: str) -> str:
    try:
        out = subprocess.run(
            ["ip", "-4", "-o", "addr", "show", "dev", iface],
            capture_output=True, text=True, timeout=5,
        ).stdout
    except (subprocess.TimeoutExpired, OSError):
        return ""
    m = re.search(r"inet (\d+\.\d+\.\d+\.\d+)", out)
    return m.group(1) if m else ""


def _ping_interval(pps: float) -> float:
    """pps=None means "flood, as fast as possible" -- ping has no such
    mode of its own that reliably clears ICMP_THRESHOLD (its built-in
    -f is paced by incoming replies unless run as root, and even then
    isn't guaranteed comfortably past 150pps), so this picks an
    explicit, aggressive interval instead."""
    if pps is None:
        return 0.001
    return max(0.001, 1.0 / pps)


class Subscriber:
    """One macvlan-backed subscriber session -- owns its dhclient
    process and (when attacking) its attack-traffic process (ping, or
    bng_flood.py for TCP_SYN/UDP)."""

    def __init__(self, n: int, gateway_ip: str):
        self.n = n
        self.iface = _iface(n)
        self.gateway_ip = gateway_ip
        self.ip = ""
        self._attack_proc: subprocess.Popen = None
        # Remembers the currently-running attack's own params (None if
        # not attacking) so resync_ip() can relaunch with the SAME
        # scenario after an IP change -- see resync_ip()'s own comment
        # for why this exists at all.
        self._attack_params: tuple = None

    def session_up(self) -> None:
        if self.ip:
            return  # already leased
        os.makedirs(_DHCP_RUN_DIR, exist_ok=True)
        subprocess.run(
            ["dhclient", "-nw", "-pf", _pidfile(self.n), "-lf", _leasefile(self.n), self.iface],
            capture_output=True, text=True, timeout=_DHCP_WAIT_S,
        )
        deadline = time.time() + _DHCP_WAIT_S
        while time.time() < deadline:
            ip = _read_iface_ip(self.iface)
            if ip:
                self.ip = ip
                self._add_source_route()
                print(f"[SUBSCRIBER] {self.iface} leased {ip}")
                return
            time.sleep(0.5)
        print(f"[SUBSCRIBER] {self.iface} did not get a DHCP lease within {_DHCP_WAIT_S}s", file=sys.stderr)

    def _add_source_route(self) -> None:
        """Real, ordinary kernel sockets bound to this subscriber's own
        IP (bng_flood.py's tcp_syn_flood/udp_flood, and `ping -I`) route
        via the kernel's real FIB lookup, which considers the packet's
        source address once a matching `ip rule` exists -- this sends
        traffic out this session's own macvlan interface, via `bng`'s
        real gateway, instead of `suscriptor`'s other (management) NIC's
        own destination-based route. (hping3 was tried here too and
        confirmed unable to deliver traffic regardless of this routing
        setup -- see bng_flood.py's own module docstring for why; this
        routing infrastructure is exactly right for genuine
        kernel-originated traffic, just not for hping3's own raw
        injection.)"""
        table = _route_table(self.n)
        _run_ip(["route", "replace", "default", "via", self.gateway_ip, "dev", self.iface, "table", str(table)])
        _run_ip(["rule", "add", "from", self.ip, "table", str(table), "priority", str(_rule_priority(self.n))])

    def _del_source_route(self) -> None:
        if not self.ip:
            return
        _run_ip(["rule", "del", "from", self.ip, "table", str(_route_table(self.n)),
                 "priority", str(_rule_priority(self.n))])
        _run_ip(["route", "flush", "table", str(_route_table(self.n))])

    def resync_ip(self) -> bool:
        """Re-reads this subscriber's real interface IP and, if it
        changed since session_up(), re-syncs everything keyed on it.

        Confirmed on a real run: accel-ppp's IPoE pool allocation does
        NOT reliably keep handing the same MAC the same IP across
        successive DHCP transactions -- this was observed repeatedly
        reassigning a live subscriber's macvlanN interface a DIFFERENT
        address, independent of dhclient's own lease-renewal timer (a
        long lease-time, roles/bng's own accel-ppp.conf.j2, cuts down
        how OFTEN this can happen but doesn't stop it outright). Without
        this, self.ip (used for the source-route rule, the running
        attack process's own --src-ip, and broadband_adapter.py's
        src_ip-keyed active_scenario.json) silently goes stale: the
        attack process keeps binding to an address no longer assigned
        to any local interface, generating zero real traffic with no
        visible error (see accel-ppp.conf.j2's own comment on this same
        failure mode). Returns True if the IP changed (caller should
        rewrite the state file)."""
        if not self.ip:
            return False
        current = _read_iface_ip(self.iface)
        if not current or current == self.ip:
            return False
        old_ip = self.ip
        self._del_source_route()
        self.ip = current
        self._add_source_route()
        print(f"[SUBSCRIBER] {self.iface} IP changed {old_ip} -> {current}, resyncing", file=sys.stderr)
        if self._attack_params is not None:
            protocol, dst_port, pps, target_ip = self._attack_params
            self.start_attack(protocol, dst_port, pps, target_ip)
        return True

    def session_down(self) -> None:
        self.stop_attack()
        self._del_source_route()
        if not self.ip and not os.path.exists(_pidfile(self.n)):
            return
        # -r (release) -- sends a real DHCPRELEASE, the trigger for
        # accel-ppp/FreeRADIUS to emit a real Accounting-Stop record
        # for this session (see this module's own docstring).
        subprocess.run(
            ["dhclient", "-r", "-pf", _pidfile(self.n), "-lf", _leasefile(self.n), self.iface],
            capture_output=True, text=True, timeout=_DHCP_WAIT_S,
        )
        for f in (_pidfile(self.n), _leasefile(self.n)):
            if os.path.exists(f):
                os.remove(f)
        self.ip = ""

    def force_refresh(self) -> None:
        """Fully re-establishes this subscriber's session (a real
        DHCPRELEASE immediately followed by a fresh DHCPDISCOVER),
        restarting whatever attack was running under the new IP.

        Used when something OUTSIDE this daemon's own knowledge
        invalidated the session server-side -- confirmed on a real run:
        telemetry/broadband_adapter.py's own apply_mitigation() blocks a
        subscriber via `accel-cmd terminate ip <ip>` directly on `bng`,
        which this daemon has no way to observe. resync_ip() alone
        doesn't catch this: the interface KEEPS its old IP locally
        (nothing forces dhclient to notice its session died until its
        own next lease renewal, which -- especially with a long
        lease-time, see accel-ppp.conf.j2's own comment on why that
        exists -- could be a long time away), so the subscriber stays a
        silent "ghost" (an IP with no real accounting happening for it
        at all) long after apply_mitigation()'s own unblock() removes
        the FreeRADIUS reject that was actually keeping it out. Called
        from the FIFO's own "kick <ip>" command, sent by
        broadband_adapter.py right after a real unblock."""
        attack_params = self._attack_params
        self.session_down()
        self.session_up()
        if attack_params is not None and self.ip:
            protocol, dst_port, pps, target_ip = attack_params
            self.start_attack(protocol, dst_port, pps, target_ip)

    def start_attack(self, protocol: str, dst_port: int, pps: float, target_ip: str) -> None:
        self.stop_attack()
        if not self.ip:
            print(f"[SUBSCRIBER] {self.iface} has no IP yet, cannot attack", file=sys.stderr)
            return
        self._attack_params = (protocol, dst_port, pps, target_ip)
        if protocol == "ICMP":
            # ping is genuine kernel-stack traffic, not hping3's raw
            # injection. Bind to the subscriber's source IP, not its
            # interface name: `ping -I macvlanN` treats an off-link
            # target as directly connected and ARPs for the target
            # itself, bypassing the source-policy route through the
            # BNG. Binding the IP lets the kernel select table 100+N
            # and its real gateway, just like the TCP/UDP generators.
            argv = ["ping", "-q", "-i", f"{_ping_interval(pps):.4f}", "-I", self.ip, target_ip]
        else:
            # TCP_SYN/UDP: bng_flood.py -- real kernel sockets bound to
            # this subscriber's own IP. See its own module docstring for
            # why hping3 can't be used here. Relies on the source-based
            # policy route _add_source_route() set up in session_up()
            # to deliver this out the right macvlan interface.
            argv = [
                sys.executable, _FLOOD_SCRIPT,
                "--protocol", "tcp_syn" if protocol == "TCP_SYN" else "udp",
                "--src-ip", self.ip, "--dst-ip", target_ip, "--dst-port", str(dst_port),
            ]
            if pps is not None:
                argv += ["--pps", str(pps)]
        # stderr appended to a real file, NOT DEVNULL -- confirmed on a
        # real run: bng_flood.py's own udp_flood() silently sending zero
        # real packets (dst_port=0 makes every sendto() fail) was
        # invisible for exactly this reason. It now prints once on a
        # real failure (see its own comment) -- discarding that here
        # would have made the fix pointless.
        with open(_FLOOD_LOG_PATH, "a") as flood_log:
            self._attack_proc = subprocess.Popen(argv, stdout=subprocess.DEVNULL, stderr=flood_log)

    def stop_attack(self) -> None:
        self._attack_params = None
        if self._attack_proc is None:
            return
        try:
            self._attack_proc.terminate()
            self._attack_proc.wait(timeout=3)
        except (subprocess.TimeoutExpired, OSError):
            try:
                self._attack_proc.kill()
            except OSError:
                pass
        self._attack_proc = None


class SubscriberPool:
    def __init__(self, target_ip: str, gateway_ip: str):
        self.target_ip = target_ip
        self.subscribers = {n: Subscriber(n, gateway_ip) for n in range(1, _MAX_SUBSCRIBERS + 1)}
        self.current_scenario = None
        # Serializes launch()/stop_attack_only()/stop_all() (driven by
        # the FIFO thread) against resync_all() (driven by run()'s own
        # background thread) -- both can start/stop the same
        # Subscriber's attack process, and that's not atomic.
        self._lock = threading.Lock()
        # Current scenario's own protocol/dst_port/count -- kept so
        # resync_all() can rewrite the state file (src_ip -> metadata)
        # after an IP change without needing the FIFO to hand them in
        # again; None protocol means "not attacking, nothing to track".
        self._active_protocol = None
        self._active_dst_port = None
        self._active_count = 0

    def _ensure_up(self, count: int) -> None:
        for n in range(1, count + 1):
            self.subscribers[n].session_up()

    def launch(self, scenario: str) -> None:
        """Switches subscribers 1..subscriber_count to this scenario's
        attack traffic; every OTHER subscriber up to _MAX_SUBSCRIBERS
        keeps (or gets put back on) the baseline's own low-rate traffic
        -- it is NEVER torn down for a scenario switch.

        Used to tear down/rebuild subscribers past subscriber_count via
        _ensure_down() (session_down(): real DHCPRELEASE + a fresh
        DHCPDISCOVER on the next _ensure_up()). Confirmed on a real run
        this is a genuine BNG-session-consistency hazard, not just
        churn: scaling the pool down then back up under load raced
        accel-ppp's own session bookkeeping on `bng`, leaving a subscriber
        the Python side believed was up (a real kernel IP on its
        macvlan) with NO matching accel-ppp session server-side --
        traffic sourced from it generated zero accounting and was
        invisible to detection, indistinguishable from the attack
        simply not existing. Per the user's own explicit direction:
        attacking should never kill sessions -- 8 stay up throughout,
        one (or a few) of them just sends more traffic. This also
        matches a real botnet's actual shape better than a pool that
        shrinks to just the attacker(s) every time one exists.
        """
        scn = build_scenario(scenario)
        baseline = SCENARIO_PARAMS[BASELINE_SCENARIO]
        count = scn["subscriber_count"]
        with self._lock:
            self._ensure_up(_MAX_SUBSCRIBERS)
            for n in range(1, count + 1):
                self.subscribers[n].start_attack(scn["protocol"], scn["dst_port"], scn["pps"], self.target_ip)
            for n in range(count + 1, _MAX_SUBSCRIBERS + 1):
                self.subscribers[n].start_attack(
                    baseline["protocol"], baseline["dst_port"], baseline["pps"], self.target_ip
                )
            self.current_scenario = scenario
            self._active_protocol = scn["protocol"]
            self._active_dst_port = scn["dst_port"]
            self._active_count = count
            self._write_state()
        print(f"[SUBSCRIBER] scenario={scenario} subscribers={count} started "
              f"(remaining {_MAX_SUBSCRIBERS - count} kept on baseline traffic)")

    def stop_attack_only(self) -> None:
        with self._lock:
            for sub in self.subscribers.values():
                sub.stop_attack()
            self._active_protocol = None
            self._active_count = 0
            self._write_state()

    def stop_all(self) -> None:
        with self._lock:
            for sub in self.subscribers.values():
                sub.session_down()
            self.current_scenario = None
            self._active_protocol = None
            self._active_count = 0
            self._write_state()

    def kick_by_ip(self, ip: str) -> None:
        """Finds whichever subscriber currently holds `ip` and forces a
        fresh session for it -- see Subscriber.force_refresh()'s own
        docstring for why. Silent no-op if no subscriber currently has
        that IP (e.g. it already resynced to a different one on its
        own, or the FIFO command arrived late)."""
        with self._lock:
            for sub in self.subscribers.values():
                if sub.ip == ip:
                    print(f"[SUBSCRIBER] kicking {sub.iface} (was {ip}) for a fresh session", file=sys.stderr)
                    sub.force_refresh()
                    break
            self._write_state()

    def resync_all(self) -> None:
        """Periodically called (see run()'s own background thread) to
        catch subscriber IP drift -- see Subscriber.resync_ip()'s own
        docstring for why this is needed at all. Only rewrites the
        state file if something actually changed, to avoid needless
        I/O every tick."""
        # resync_ip() itself is a cheap no-op for any subscriber with no
        # current IP (torn down / never brought up), so just checking
        # every slot here is simpler than tracking exactly which ones
        # are currently up.
        with self._lock:
            changed = False
            for sub in self.subscribers.values():
                if sub.resync_ip():
                    changed = True
            if changed:
                self._write_state()

    def _write_state(self) -> None:
        """src_ip -> {protocol, dst_port} for every subscriber currently
        attacking, keyed by their REAL DHCP-assigned IP -- see this
        module's own top-of-file comment on why broadband_adapter.py
        needs this alongside FreeRADIUS's real rate data."""
        state = {}
        if self._active_protocol is not None:
            for n in range(1, self._active_count + 1):
                ip = self.subscribers[n].ip
                if ip:
                    state[ip] = {"protocol": self._active_protocol, "dst_port": self._active_dst_port}
        try:
            with open(_STATE_PATH, "w") as f:
                json.dump(state, f)
        except OSError as exc:
            print(f"[SUBSCRIBER] cannot write {_STATE_PATH}: {exc}", file=sys.stderr)


def _handle_line(pool: SubscriberPool, line: str) -> None:
    parts = line.strip().split(None, 1)
    if not parts:
        return
    cmd = parts[0]
    try:
        if cmd == "baseline":
            pool.launch(BASELINE_SCENARIO)
        elif cmd == "attack" and len(parts) == 2 and parts[1] in SCENARIOS:
            pool.launch(parts[1])
        elif cmd == "stop":
            # Falls back to the standing baseline, same posture as every
            # other domain in this project -- broadband's benign traffic
            # must never simply vanish.
            if pool.current_scenario == BASELINE_SCENARIO:
                pool.stop_attack_only()
                pool.launch(BASELINE_SCENARIO)
            else:
                pool.launch(BASELINE_SCENARIO)
        elif cmd == "stop_all":
            pool.stop_all()
        elif cmd == "kick" and len(parts) == 2:
            # Sent by telemetry/broadband_adapter.py's own
            # apply_mitigation() right after a real unblock -- see
            # Subscriber.force_refresh()'s own docstring for why.
            pool.kick_by_ip(parts[1])
        else:
            print(f"[SUBSCRIBER] unknown command: {line!r}", file=sys.stderr)
    except (OSError, ValueError) as exc:
        print(f"[SUBSCRIBER] command {line!r} failed: {exc}", file=sys.stderr)


def _resync_loop(pool: SubscriberPool) -> None:
    while True:
        time.sleep(_RESYNC_INTERVAL_S)
        try:
            pool.resync_all()
        except (OSError, ValueError) as exc:
            print(f"[SUBSCRIBER] resync failed: {exc}", file=sys.stderr)


class _StateHTTPHandler(BaseHTTPRequestHandler):
    """Serves GET /active_scenario -- the same JSON _write_state() (see
    SubscriberPool above) already writes to _STATE_PATH, just over a
    plain local socket instead of a remote `cat` over SSH.

    Replaces telemetry/broadband_adapter.py's old _ssh_suscriptor(["cat",
    ...]) call: that spawned a fresh SSH connection (a real fork/exec on
    both ends, ~0.5s just for the handshake, confirmed on a real run) on
    EVERY collect() cycle to read a file that changes only when an
    attack starts/stops -- most polls saw the exact same bytes. A plain
    HTTP GET over a socket eventlet's own monkey-patching already makes
    cooperative (unlike subprocess.run(), see this project's many
    tpool.execute() call sites) costs a single local round-trip with no
    process spawn on either side.

    BaseHTTPRequestHandler/ThreadingHTTPServer, not a new Flask/wsgi
    dependency -- this endpoint is one read-only route returning a small
    file's contents, not worth a new package for."""

    def log_message(self, format, *args):  # noqa: A002 -- stdlib's own name
        pass  # BaseHTTPRequestHandler logs every request to stderr by
        # default, which would otherwise spam this daemon's own log file
        # with one line per COLLECT_INTERVAL poll, forever.

    def do_GET(self):
        if self.path != "/active_scenario":
            self.send_response(404)
            self.end_headers()
            return
        try:
            with open(_STATE_PATH, "rb") as f:
                body = f.read()
        except OSError:
            body = b"{}"
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)


def _http_loop(port: int) -> None:
    server = ThreadingHTTPServer(("0.0.0.0", port), _StateHTTPHandler)
    server.serve_forever()


def run(fifo_path: str, target_ip: str, gateway_ip: str, start_baseline: bool) -> None:
    os.makedirs(os.path.dirname(fifo_path), exist_ok=True)
    if not os.path.exists(fifo_path):
        os.mkfifo(fifo_path, 0o666)
        # os.mkfifo()'s own mode argument is masked by this (root)
        # process's umask, same as open()/mkdir() -- confirmed on a
        # real run: with a typical 0022 umask, the FIFO actually ended
        # up 0644 (owner-write only), silently blocking every SSH-based
        # writer that isn't root. telemetry/broadband_adapter.py's own
        # _ssh_suscriptor() calls connect as a plain non-root user
        # (BNG_DIST_SUSCRIPTOR_SSH_USER) -- its FIFO writes (including
        # apply_mitigation()'s own "kick" command) failed with a silent
        # "Permission denied" this way for a long stretch of debugging,
        # while ansible's own ad-hoc test commands worked fine (they
        # run as root via become=True), masking the bug entirely until
        # traced by hand against a live run. chmod here forces the
        # exact requested bits regardless of umask.
        os.chmod(fifo_path, 0o666)

    pool = SubscriberPool(target_ip=target_ip, gateway_ip=gateway_ip)
    if start_baseline:
        pool.launch(BASELINE_SCENARIO)

    threading.Thread(target=_resync_loop, args=(pool,), daemon=True).start()
    threading.Thread(target=_http_loop, args=(_HTTP_PORT,), daemon=True).start()

    while True:
        with open(fifo_path, "r") as f:
            for line in f:
                if line.strip():
                    _handle_line(pool, line)


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--target-ip", required=True)
    p.add_argument("--gateway-ip", required=True, help="bng's own access-side IP -- the per-subscriber default route added by _add_source_route() goes via this address")
    p.add_argument("--parent-interface", required=True, help="informational only -- macvlans are created by roles/suscriptor's setup_macvlans.sh.j2, not by this script")
    p.add_argument("--fifo", default="/run/bng-agent/cmd")
    p.add_argument("--no-baseline", action="store_true")
    args = p.parse_args()

    if sys.platform != "linux":
        print("ERROR: needs Linux (raw sockets, dhclient) -- run this on suscriptor, not here.", file=sys.stderr)
        sys.exit(1)

    run(fifo_path=args.fifo, target_ip=args.target_ip, gateway_ip=args.gateway_ip, start_baseline=not args.no_baseline)


if __name__ == "__main__":
    main()
